api/urls.py
from django.urls import path
from . import views


app_name = 'api'
urlpatterns = [
    # post views
    path('print/', views.Print, name='print'),
    path('print/<int:pk>/', views.PrintVisitante, name='print'),
]

cadastro/urls.py
from django.urls import path
from . import views


app_name = 'cadastro'
urlpatterns = [
    # post views
    path('cadastro/', views.cadastro, name='cadastro'),
    path('', views.home, name='home'),
]

toroku/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cadastro.urls', namespace='cadastro')),
    path('api/', include('api.urls', namespace='api')),
    path('accounts/', include('django.contrib.auth.urls')),
]

api/models.py
from django.db import models

# Create your models here.

cadastro/models.py
from django.db import models

SEXO_CHOICES = (
    (0, 'Não Informado'),
    (1, 'Homem'),
    (2, 'Mulher'),
)
TIPO_CHOICES = (
    (0, 'Visitante'),
    (1, 'Lojista'),
)

# Create your models here.
class Visitante(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    nome = models.CharField(max_length=50)
    email = models.EmailField('Email')
    telefone = models.CharField(max_length=15,help_text='(xx)xxxxx-xxxx', blank=True)
    documento = models.CharField('CPF/CNPJ',max_length=50)
    aniversario = models.DateField('aniversario', blank=True)
    sexo = models.PositiveSmallIntegerField(choices=SEXO_CHOICES, default=0)
    tipo = models.PositiveSmallIntegerField(choices=TIPO_CHOICES, default=0)
    CodigoBarra = models.CharField('Crachá',max_length=50, blank=True)
    impresso = models.BooleanField(default=False)

cadastro/forms.py
from django import forms

from .models import Visitante

class DateInput(forms.DateInput):
    input_type = 'date'


class VisitanteForm(forms.ModelForm):

    class Meta:
        model = Visitante
        fields = ('nome', 'email','telefone','documento','aniversario','sexo','tipo','CodigoBarra')
        widgets = {
            'aniversario': DateInput()
        }

api/views.py
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from cadastro.models import Visitante
from rest_framework import generics
from api.serializers import VisitanteSerializer

@api_view(['GET'])
def Print(request):
    queryset = Visitante.objects.filter(impresso=False)
    serializer = VisitanteSerializer(queryset, many=True)
    return Response(serializer.data)

@api_view(['GET','PUT'])
def PrintVisitante(request, pk):
    """
    Retrieve, update or delete a person instance.
    """
    try:
        visitante = Visitante.objects.get(pk=pk)
    except Visitante.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = VisitanteSerializer(visitante)
        return Response(serializer.data)

    elif request.method == 'PUT':
        serializer = VisitanteSerializer(visitante, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

cadastro/views.py
from django.shortcuts import render
from .models import *
from .forms import VisitanteForm
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def cadastro(request):
    if request.method == "POST":
        form = VisitanteForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return render(request, 'cadastro/sucesso.html', {'form': form})
    else:
        form = VisitanteForm()

    return render(request, 'cadastro/visitante.html', {'form': form})

def home(request):
    return render(request, 'cadastro/home.html')

templates/base.html
{% load staticfiles %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href={% static "toroku/bootstrap.min.css" %} integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link href={% static "toroku/narrow-jumbotron.css"  %} rel="stylesheet">
    <title>{% block title %}Toroku{% endblock %}</title>
  </head>
  <body>
    <div class="container">

      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills float-right">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <p class="nav-link" href="#">Olá, {{user.username}}</p>
            </li>
            <li class="nav-item">
               <a class="nav-link " href="{% url 'logout' %}">Sair</a>
            </li>
            {% endif %}
          </ul>
        </nav>
        <h3 class="text-muted">Toroku</h3>
      </div>

      {% block content %}
       {% endblock %}

    </div>


    <script src={% static "toroku/jquery-3.2.1.slim.min.js" %} integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src={% static "toroku/popper.min.js" %} integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src={% static "toroku/bootstrap.min.js" %} integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/cadastro/home.html
{% extends '../base.html' %}
{% block content %}

<div class="jumbotron">
  <h1 class="display-3">Body Style</h1>
  <p class="lead">Sistema para cadastro de visitantes!</p>
  {% if user.is_authenticated %}
  <p><a class="btn btn-lg btn-success" href="{% url 'cadastro:cadastro' %}" role="button">Cadastro</a></p>
  {% else %}
  <p><a class="btn btn-lg btn-success" href="{% url 'login' %}" role="button">Login</a></p>
  {% endif %}
</div>
<footer class="footer">
        <p>Desenvolvido por @felipeiasi</p>
      </footer>
{% endblock %}

templates/cadastro/sucesso.html
{% extends '../base.html' %}
{% block content %}

<div class="jumbotron">
  <h1 class="display-3">Cadastrado com sucesso!</h1>
  <p class="lead"></p>
  <p><a class="btn btn-lg btn-success" href="{% url 'cadastro:cadastro' %}" role="button">Novo cadastro</a></p>
</div>
<footer class="footer">
        <p>Desenvolvido por @felipeiasi</p>
      </footer>
{% endblock %}

templates/cadastro/visitante.html
{% load staticfiles %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Cadastro Visitantes</title>
  </head>
  <body>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            LOGO
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 offset-md-3">
            <form method="POST" class="post-form">
              {% csrf_token %}
            <div class="card">
              <h5 class="card-header">Cadastro Visitante</h5>
              <div class="card-body">
                <h5 class="card-title">Preencha os campos:</h5>
                <p class="card-text">{{form|crispy }}</p>
                <button type="submit" class="btn btn-primary">Enviar</button>
              </div>
            </div>
              </form>
          </div>
        </div>
      </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>